# frozen_string_literal: true

# Standard Webhooks signature verification — cross-implementation parity.
#
# The expected signature headers below were generated by the ACTUAL TypeScript
# signer that the Mailtea platform delivers webhooks with, so this Ruby
# implementation is checked against real platform output rather than against
# itself. The same vectors are pinned in the Python SDK's test suite.
#
#   SECRET_A       = "whsec_dGVzdC1zaWduaW5nLWtleS0zMi1ieXRlcy1sb25n"
#   SECRET_B       = "whsec_cm90YXRpb24tc2VjcmV0LTMyLWJ5dGVzLWxvbmctdGVzdA"
#   MSG_ID         = "msg_2xyzABC123"
#   TIMESTAMP      = 1700000000
#   PAYLOAD        = '{"id":"evt_test","type":"email.delivered","data":{"email_id":"txemail_1"}}'
#   signWebhook(A) = "v1,txVPz2dd9nKoJKXT5SM0Ryfb0Tb5H+HRpz4nI/xpw+Q="
#   signWebhook(B) = "v1,c1hy0+MUcGBKxkM1Y96IQmkXAe2lGJY2AeZIQvKBJvg="

require "minitest/autorun"
require "mailtea"

class WebhookSigningTest < Minitest::Test
  SECRET_A = "whsec_dGVzdC1zaWduaW5nLWtleS0zMi1ieXRlcy1sb25n"
  SECRET_B = "whsec_cm90YXRpb24tc2VjcmV0LTMyLWJ5dGVzLWxvbmctdGVzdA"
  MSG_ID = "msg_2xyzABC123"
  TIMESTAMP = 1_700_000_000
  PAYLOAD = '{"id":"evt_test","type":"email.delivered","data":{"email_id":"txemail_1"}}'

  HEADER_A = "v1,txVPz2dd9nKoJKXT5SM0Ryfb0Tb5H+HRpz4nI/xpw+Q="
  HEADER_B = "v1,c1hy0+MUcGBKxkM1Y96IQmkXAe2lGJY2AeZIQvKBJvg="
  # During rotation the platform signs with both secrets and sends both tokens.
  ROTATION_HEADER = "#{HEADER_A} #{HEADER_B}"

  def verify(header, **options)
    Mailtea.verify_webhook_signature(SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, header,
                                     **{ now: TIMESTAMP }.merge(options))
  end

  # --- cross-implementation: the Ruby signer reproduces the TypeScript output ---
  def test_sign_matches_the_typescript_vector
    assert_equal HEADER_A, Mailtea.sign_webhook(SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD)
    assert_equal HEADER_B, Mailtea.sign_webhook(SECRET_B, MSG_ID, TIMESTAMP, PAYLOAD)
  end

  def test_verify_accepts_a_header_the_platform_signed
    assert verify(HEADER_A)
  end

  def test_sign_then_verify_round_trips
    header = Mailtea.sign_webhook(SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD)

    assert verify(header)
  end

  def test_the_timestamp_may_arrive_as_the_string_the_header_carries
    assert Mailtea.verify_webhook_signature(SECRET_A, MSG_ID, TIMESTAMP.to_s, PAYLOAD,
                                            HEADER_A, now: TIMESTAMP)
  end

  def test_a_tampered_body_is_rejected
    tampered = PAYLOAD.sub("txemail_1", "txemail_2")

    refute Mailtea.verify_webhook_signature(SECRET_A, MSG_ID, TIMESTAMP, tampered, HEADER_A,
                                            now: TIMESTAMP)
  end

  def test_a_different_message_id_is_rejected
    refute Mailtea.verify_webhook_signature(SECRET_A, "msg_other", TIMESTAMP, PAYLOAD,
                                            HEADER_A, now: TIMESTAMP)
  end

  def test_a_signature_from_another_secret_is_rejected
    refute verify(HEADER_B)
  end

  def test_an_expired_timestamp_is_rejected_and_the_window_is_configurable
    refute verify(HEADER_A, now: TIMESTAMP + 301)
    refute verify(HEADER_A, now: TIMESTAMP - 301)
    assert verify(HEADER_A, now: TIMESTAMP + 299)
    assert verify(HEADER_A, now: TIMESTAMP + 3600, tolerance_seconds: 7200)
  end

  # Standard Webhooks allows key rotation: the platform signs one delivery with
  # both secrets, and either token matching is a pass.
  def test_a_rotation_header_passes_on_either_token
    assert verify(ROTATION_HEADER)
    assert Mailtea.verify_webhook_signature(SECRET_B, MSG_ID, TIMESTAMP, PAYLOAD,
                                            ROTATION_HEADER, now: TIMESTAMP)
  end

  def test_a_malformed_header_returns_false_rather_than_raising
    ["", "   ", "garbage", "v1", "v1,", "v2,#{HEADER_A.split(",").last}",
     HEADER_A.split(",").last].each do |header|
      refute verify(header), "expected #{header.inspect} to be rejected"
    end
  end

  def test_a_non_numeric_timestamp_is_rejected_rather_than_rounding_to_the_epoch
    refute Mailtea.verify_webhook_signature(SECRET_A, MSG_ID, "not-a-number", PAYLOAD,
                                            HEADER_A, now: TIMESTAMP)
    refute Mailtea.verify_webhook_signature(SECRET_A, MSG_ID, nil, PAYLOAD, HEADER_A,
                                            now: TIMESTAMP)
  end

  # A secret minted with either base64 alphabet, padded or not, has to decode to
  # the same key — the platform's own decoder is lenient about both.
  def test_the_secret_decodes_from_base64url_and_unpadded_forms
    unpadded = SECRET_A.sub(/=+\z/, "")

    assert_equal(
      Mailtea.sign_webhook(SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD),
      Mailtea.sign_webhook(unpadded, MSG_ID, TIMESTAMP, PAYLOAD)
    )
  end

  # The comparison must not leak how much of the digest matched. OpenSSL's
  # secure_compare is the only equality this file may reach for.
  def test_the_comparison_is_constant_time
    source = File.read(File.expand_path("../lib/mailtea/webhook_signing.rb", __dir__))

    assert_includes source, "OpenSSL.secure_compare"
    refute_match(/signature\s*==\s*expected/, source)
  end
end
